<div id="beer-slider" class="coda-slider">
    <div class="home_slide img_1">
        <h2 class="title">&nbsp;</h2>
        <h2>WELCOME TO PHOENIX BEERS</h2>
        <p>Not a member yet? You should be! So what are you waiting for?<br /><span class="red-text">Liquor Retailers, Join Now!</span></p>
        <p>THE WORLD&rsquo;S BEST BEERS AND CIDERS ARE OUR PASSION. WE HOPE TO MAKE THEM YOUR PASSION TOO.</p>
    </div>
    <div class="home_slide img_2">
        <h2 class="title">&nbsp;</h2>
        <h2>MEMBER BENEFITS</h2>
        <p>WE CARE ABOUT BEER AND YOU</p>
        <p>PHOENIX BEERS GIVES ATTENTIVE AND QUALITY CUSTOMER SERVICE, WITH GREAT CARE GIVEN TO YOUR ENQUIRY.</p>
    </div>
    <div class="home_slide img_3">
        <h2 class="title">&nbsp;</h2>
        <h2>MEMBER BENEFITS</h2>
        <p>FRESH IS BEST</p>
        <p>PHOENIX BEERS ENSURES THE QUALITY OF FLAVOUR AND FRESHNESS OF OUR CRAFT BEERS THROUGH REFRIGERATED SHIPPING AND STORAGE. CRAFT BEER THE WAY IT IS MEANT TO BE!</p>
    </div>
    <div class="home_slide img_4">
        <h2 class="title">&nbsp;</h2>
        <h2>MEMBER BENEFITS</h2>
        <p>CRAFT BEER IS OUR LIFE</p>
        <p>WE ARE CONTINUALLY WORKING WITH OUR VENUES TO OFFER EVENT OPPORTUNITIES, VIA SPECIALTY BEERS AND GUESTS, THAT ALLOW THEM TO GROW THEIR BRAND RECOGNITION IN THE CRAFT BEER COMMUNITY.</p>
    </div>
    <div class="home_slide img_5">
        <h2 class="title">&nbsp;</h2>
        <h2>MEMBER BENEFITS</h2>
        <p>SPEED AND PERFORMANCE</p>
        <p>UNDERSTANDING THAT SPEED AND CONVENIENCE ARE OF THE UP-MOST IMPORTANCE IN THIS INDUSTRY, WE OFFER NEXT DAY DELIVERY IF YOU ARE IN THE METRO AREA.</p>
    </div>
    <div class="home_slide img_6">
        <h2 class="title">&nbsp;</h2>
        <h2>MEMBER BENEFITS</h2>
        <p>BIGGEST RANGE IN AUSTRALIA</p>
        <p>PHOENIX BEERS HAVE THE WIDEST RANGE OF INTERNATIONAL CRAFT BREWERIES AVAILABLE IN AUSTRALIA, JUST FOR YOU.</p>
    </div>
</div>