<?php $base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>
<div class="sm">
  <a target="_blank" href="http://facebook.com"><img class="footer-sl-img" src=<?php echo $base_url."wysiwyg/icons/PB_bottom_fb2.png"; ?> /></a>
  <a target="_blank" href="http://twitter.com"><img class="footer-sl-img" src=<?php echo $base_url."wysiwyg/icons/PB_bottom_tw.png"; ?> /></a>
  <a target="_blank" href="http://youtube.com"><img class="footer-sl-img" src=<?php echo $base_url."wysiwyg/icons/PB_bottom_yu.png"; ?> /></a>
</div>
