<script>
    function writeCookie(key, value, days) {
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
            var expires = "; expires=" + date.toGMTString();
        }
        else
            var expires = "";
        document.cookie = key + "=" + value + expires + "; path=/";
    }

    function readCookie(key) {
        var nameEQ = key + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ')
                c = c.substring(1, c.length);
            if (c.indexOf(nameEQ) == 0)
                return c.substring(nameEQ.length, c.length);
        }
        return null;
    }

    function saidYes() {
        writeCookie('ibs-magento', 'ok', 1);
        window.location = "/home";
    }

    function saidNo() {
        // window.location = "/licence";
        document.getElementById('no').style.display = 'block';
        document.getElementById('yes').style.display = 'none';
    }

    // at page init
    if ('ok' == readCookie('ibs-magento')) {
        window.location = "/home";
    }

</script>

<div id="welcome-contents">
    <div id="home-login-page" class="registered-users shadow">
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <?php echo $this->getChildHtml('customer.form.login.extra') ?>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
            <div class="content">
                <h1 id="login-title">RETAIL MEMBERS</h1>

                <div class="input-box-welcome">
                    <button id="signin-btn" type="button" onclick="window.location = '<?php echo $this->getCreateAccountUrl() ?>';">
                        <span><span><?php echo $this->__('Sign in') ?></span></span>
                    </button>
                </div>

                <div class="input-box-welcome">
                    <input type="text" name="login[username]"
                           value="<?php echo $this->escapeHtml($this->getUsername()) ?>"
                           id="email" class="input-text required-entry validate-email"
                           title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
                </div>

                <div class="input-box-welcome">
                    <input type="password" name="login[password]"
                           class="input-text required-entry validate-password"
                           id="pass" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
                </div>

                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </div>

            <div class="input-box-welcome">
                <a href="<?php echo $this->getForgotPasswordUrl() ?>" id="pwd-forget-link"
                   class="f-left"><?php echo $this->__('Forgotten your password?') ?>
                </a>
            </div>
            <br>
            <br>

            <div id="submit-btn-wrapper">
                <button type="submit" class="welcome-btn shadow"
                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>"
                        name="send" id="send2"><span><span><?php echo $this->__('Go Fetch Woof :') ?></span></span></button>
            </div>



        </form>

    </div>

    <div id="main-welcome-box" class="shadow">
        <div id="welcome-main-div">
            <h1>WELCOME TO PHOENIX BEERS</h1>
            <h4>Are you of legal drinking age in your country?</h4>
        </div>
        <div id="welcome-btn-box">
            <div class="welcome-btn shadow"  onclick="saidYes()">
                <a id="btn_yes" href="#">Yes</a>
            </div>
            <div class="welcome-btn shadow"  onclick="saidNo()">
                <a id="btn_no" href="#">No</a>
            </div>
        </div>
<br/>
        <div id="yes">
            <h6 class="text-white home-msg-lg">Licence Details</h6>
            <p class="text-white home-msg">
                No. 616 010 3052<br/>
                Wholesaler’s Licence<br/>
                Phoenix Beers Pty Ltd<br/>
                A: Unit 8, 10 Dewar Street,<br/>
                Morley WA 6062<br/>
                P: 08 9275 0955
            </p>

            <h6 class="text-white home-msg-lg home-yes">WARNING</h6>
            <p class="text-white home-msg home-yes">
                Under the Liquor Control Act 1988, it is an offence:
                <ul><li class="home-msg-li">To sell or supply liquor to a person under the age
                        of 18 years on licensed or regulated premises; or</li>
                <li class="home-msg-li">For a person under the age of 18 years to purchase,
                    or attempt to purchase, liquor on licensed or regulated premises.</li>
                </ul>
            </p>
        </div>

        <div id="no">
            <h6 class="text-white home-msg-lg home-no">WARNING NO ACCESS</h6>
            <p class="text-white home-msg home-no">
                Under the Liquor Control Act 1988, it is an offence:
                <ul><li class="home-msg-li">To sell or supply liquor to a person under the age
                        of 18 years on licensed or regulated premises; or</li>
                <li class="home-msg-li">For a person under the age of 18 years to purchase,
                    or attempt to purchase, liquor on licensed or regulated premises.</li>
                </ul>
            </p>
        </div>

    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('login-form', true);
//]]>
</script>
