<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
  <div class="sidebar_item">
      <div class="filter_title">
        <h2 class="title">MEMBER LOG IN</h2>
      </div>
      <?php echo $this->getMessagesBlock()->toHtml() ?>
      <?php /* Extensions placeholder */ ?>
      <?php echo $this->getChildHtml('customer.form.login.extra')?>
      <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
          <?php echo $this->getBlockHtml('formkey'); ?>

          <div class="beer-login-box">
              <div class="input-box">
                  <input type="text" name="login[username]"
                    value="<?php echo $this->escapeHtml($this->getUsername()) ?>"
                    id="email" class="input-text required-entry validate-email"
                    title="Email" placeholder="Email"/>

                  <button type="button"
                    title="<?php echo Mage::helper('core')->quoteEscape($this->__('Create an Account')) ?>"
                    class="beer-btn beer-red btn-fix btn-w75"
                    onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';">
                    JOIN IBS
                  </button>
              </div>
              <div class="input-box">
                  <input type="password" name="login[password]"
                    class="input-text required-entry validate-password"
                    id="pass" title="Password" placeholder="Password"/>

                    <button type="submit" class="beer-btn beer-white btn-fix btn-w75"
                      title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>" name="send"
                      id="send2">SIGN IN
                    </button>
              </div>
              <div class="input-box forgot-pwd-box">
                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="forgot-pwd">
                  Forgotten your password?
                </a>
                &nbsp;&nbsp;Remember me
                <input type="checkbox" name="remember_me" value="0" />
              </div>
          </div>
      </form>
      <script type="text/javascript">
      //<![CDATA[
          var dataForm = new VarienForm('login-form', true);
      //]]>
      </script>
      <p>&nbsp;</p>
  </div>
<?php else: ?>
<?php $customer = Mage::getSingleton('customer/session')->getCustomer(); ?>
  <div class="sidebar_item">
      <div class="filter_title">
        <h2 class="title"> <?php echo $customer->getName(); ?> </h2>
      </div>
      <div class="beer-login-box">
          <div class="input-box">
            <a href="customer/account/index" class="beer-btn beer-white btn-w110">
              MY ACCOUNT
            </a>
            <a href="contact-us" class="beer-btn beer-red btn-w110">
              CONTACT US
            </a>
          </div>
          <div class="input-box">
            <a href="customer/account/index" class="beer-btn beer-white btn-w110">
              PROFILE
            </a>
            <a href="customer/account/logout" class="beer-btn beer-white btn-w110">
              SIGN OUT
            </a>
          </div>
      </div>
      <p>&nbsp;</p>
  </div>

<?php endif;?>
