<script src="<?php echo $this->getJsUrl('slideshow/jquery.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('slick/slick.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('slideshow/jquery.easing.1.3.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('codaslider/jquery.coda-slider-3.0.js'); ?>" type="text/javascript"></script>
<link href="<?php echo $this->getSkinUrl('codaslider/css/coda-slider.css'); ?>" type="text/css" rel="stylesheet"></link>
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function(){
	jQuery('#beer-slider').codaSlider({
		autoSlide:true,
		autoHeight:false,
		dynamicTabsPosition: "bottom"
	});
});
</script>
