<?php
/**
 * @category   	MagPassion Theme
 * @package    	MagPassion_Sample
 * @author     	MagPassion
 * @email		magentopassion@gmail.com
 * @copyright   Copyright (c) 2013 MagentoPassion. (http://www.magentopassion.com)
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="mp_header">
    	
    		<?php echo $this->getChildHtml('header') ?>
    	
    </div>
    <div class="mp_body">
        <div class="mp_inner">
	        <div class="main-container col2-left-layout">
	            <div class="main">
	                <?php echo $this->getChildHtml('breadcrumbs') ?>
	                <div class="col-main">
	                    <?php echo $this->getChildHtml('global_messages') ?>
	                    <?php echo $this->getChildHtml('content') ?>
	                </div>
	                <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
	            </div>
	        </div>
	        
	    </div>
    </div>
    <div class="mp_footer">
		<div class="mp_inner">
			<?php echo $this->getChildHtml('footer') ?>
	        <?php echo $this->getChildHtml('before_body_end') ?>
		</div>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
