<?php
/**
 * @category   	MagPassion Theme
 * @package    	MP_Fafree
 * @author     	MagPassion
 * @email	magentopassion@gmail.com
 * @copyright   Copyright (c) 2013 MagentoPassion. (http://www.magpassion.com)
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="mp_toplink">
    <div class="mp_inner">
	 <div class="quick-access">
        <?php echo $this->getChildHtml('store_language') ?>
        <?php echo $this->getChildHtml('topBar') ?>
        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?></p>
        <?php echo $this->getChildHtml('topLinks') ?>
        </div>
    </div>
</div>
<div class="mp_inner clearer" style="margin-top: 53px;">
    <div class="mp_logo"> 
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>    
    </div>
    <?php echo $this->getChildHtml('topContainer'); ?>
    <div class="mp_nav">
    	<?php echo $this->getChildHtml('topMenu') ?>
    </div>
</div>

<div class="mp_topbar mp_inner">
	
</div>

<?php if ($this->getIsHomePage()):?>
<?php
    $mp_homeinfo = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('home_info');
    $mp_video = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('home_video');
    

    $helper = Mage::helper('cms');
    $processor = $helper->getPageTemplateProcessor();
    //echo $processor->filter($block->getContent()); 

?>

<div class="home_featured clearer">
    <div class="mp_inner clearer">
        <div class="mp_homeinfo">
            <?php if($mp_homeinfo->getContent()):?>
                <h3><?php echo $mp_homeinfo->getTitle(); ?></h3>
                <div class="block-content">
                    <?php echo $processor->filter($mp_homeinfo->getContent()); ?>
                </div>
            <?php else: ?>
                    please create static block with id = "home_info".
            <?php endif;?>
        </div>
        <div class="mp_video">
            <?php if($mp_video->getContent()):?>

                    <?php echo $processor->filter($mp_video->getContent()); ?>

            <?php else: ?>
                    please create static block with id = "home_video".
            <?php endif;?>
        </div>
    </div>
</div>
<?php endif;?>