<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-gift-products">

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 20; //$this->getColumnCount(); ?>
    <div class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col" id="prod-gift-slider">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <div class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 150; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="product-info">
                    <h2 class="product-name">
                      <a href="<?php echo $_product->getProductUrl() ?>"
                        title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                      </a>
                    </h2>
                    <?php
                    echo Mage::getSingleton('catalog/product')->load($_product->getId())->getAttributeText('style');
                    ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>
<script>jQuery.noConflict()</script>
<script type="text/javascript">
  jQuery(document).ready(function($) {
    $('#prod-gift-slider').slick({
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 3,
      accessibility: true,
      arrows: true
    });
  });
</script>
</div>
<?php endif; ?>
