<nav id="nav-tp">
    <ol class="nav-top">
        <li class="level0 nav-1 first active">
        	<a class="level0" href="<?php echo Mage::getBaseUrl(); ?>home">HOME</a>
      	</li>
        <li class="level0 nav-2">
        	<a class="level0" href="<?php echo Mage::getBaseUrl(); ?>beers">Beers</a>
      	</li>
        <li class="level0 nav-3">
        	<a class="level0" href="<?php echo Mage::getBaseUrl(); ?>cider-and-spirits">Cider & Spirits</a>
      	</li>
        <li class="level0 nav-3">
      		<a class="level0" href="<?php echo Mage::getBaseUrl(); ?>beer-styles">Beer Styles</a>
    		</li>
        <li class="level0 nav-4">
      		<a class="level0" href="<?php echo Mage::getBaseUrl(); ?>gift-packs">Gift Packs</a>
    		</li>
    </ol>
</nav>
