<script>
    function loadPage(val)
    {
        window.location.assign(val);
    }
</script>


<div id="beer-slider" class="coda-slider">
    <div class="del_rep_slide img_1">
        <h2 class="title">South</h2>
        <div class="left">
            <div class="image">&nbsp</div>
            <select onchange="loadPage(this.value)">
                <option value="dnr">Head Office</option>
                <option selected value="dnr-nsw">New South Wales</option>
                <option value="dnr-vct">Victoria</option>
                <option value="dnr-qns">Queensland</option>
            </select>            
        </div>
        <div class="right">
            <h3>Bringing Phoenix Beer to you In NSW</h3>
            <p>Territory Manager: Simon Groot<br/>Email: nswsales@phoenixbeers.com.au<br/>Mobile: 0404 490 635</p>
            <h3>Delivery Information</h3>
            <p class="small">Please be aware that the following cut off times apply for next day deliveries and any orders placed after this will be delivered 2 days later. All times quoted are Western Standard Times. Please be aware of daylight savings as Western Australia does not practise DST you will need to add 1 hour to the below times when DST applies. </p>
            <p>Metro Deliveries: 9:30am<br/>Regional Deliveries: 7:30am</p>
        </div>
    </div>
    <div class="del_rep_slide img_2">
        <h2 class="title">North</h2>
        <div class="left">
            <div class="image">&nbsp</div>
            <select onchange="loadPage(this.value)">
                <option value="dnr">Head Office</option>
                <option selected value="dnr-nsw">New South Wales</option>
                <option value="dnr-vct">Victoria</option>
                <option value="dnr-qns">Queensland</option>
            </select>            
        </div>
        <div class="right">
            <h3>Bringing Phoenix Beer to you In NSW</h3>
            <p>Territory Manager: Simon Groot<br/>Email: nswsales@phoenixbeers.com.au<br/>Mobile: 0404 490 635</p>
            <h3>Delivery Information</h3>
            <p class="small">Please be aware that the following cut off times apply for next day deliveries and any orders placed after this will be delivered 2 days later. All times quoted are Western Standard Times. Please be aware of daylight savings as Western Australia does not practise DST you will need to add 1 hour to the below times when DST applies. </p>
            <p>Metro Deliveries: 9:30am<br/>Regional Deliveries: 7:30am</p>
        </div>
    </div>
</div>