<?php
$pb_category = (isset($_GET['pb_category']) && !empty($_GET['pb_category']))?$_GET['pb_category']:null;
$pb_country = (isset($_GET['pb_country']) && !empty($_GET['pb_country']))?$_GET['pb_country']:null;
$pb_brewery = (isset($_GET['pb_brewery']) && !empty($_GET['pb_brewery']))?$_GET['pb_brewery']:null;
$collection = array();

function breweryHistory($pb_category, $pb_brewery) {
  $attribute_id = 2; //brewery
  $collection = Mage::getModel('aove/options')->getCollection();
  $collection->addFieldToFilter('attribute_id', $attribute_id);
  $collection->addFieldToFilter('title', $pb_brewery);
  $collection->addFieldToFilter('perent_id', $pb_category);
  return $collection;
}

function countryHistory($pb_category, $pb_country) {
  $attribute_id = 1; //country
  $collection = Mage::getModel('aove/options')->getCollection();
  $collection->addFieldToFilter('attribute_id', $attribute_id);
  $collection->addFieldToFilter('title', $pb_country);
  $collection->addFieldToFilter('perent_id', $pb_category);
  return $collection;
}

function getMediaUrl($img) {
  $base_url = Mage::getBaseUrl();
  return $base_url."media/".$img;
}

function getContent($c) {
  $s1 = str_replace('src="{{media url="wysiwyg/', "src='".getMediaUrl(""), $c);
  return str_replace('"}}"', "'", $s1);
}

if($pb_category != null && $pb_country != null && $pb_brewery != null) { // brewery history
  $collection = breweryHistory($pb_category, $pb_brewery);
}
elseif($pb_category != null && $pb_country != null) { // country history
  $collection = countryHistory($pb_category, $pb_country);
}
else { // do nothing
  $collection = array();
}
?>

<script src="<?php echo $this->getJsUrl('slideshow/jquery.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('slick/slick.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('slideshow/jquery.easing.1.3.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('codaslider/jquery.coda-slider-3.0.js'); ?>" type="text/javascript"></script>
<link href="<?php echo $this->getSkinUrl('codaslider/css/coda-slider.css'); ?>" type="text/css" rel="stylesheet"></link>
<style>
.hi-left-img {
  width: 250px;
}
.hi-left-img-div {
  display: inline-block;
  float: left;
}
</style>
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function(){
	jQuery('#beer-history').codaSlider({
		autoSlide:true,
		autoHeight:false,
		dynamicTabsPosition: "bottom"
	});
});
</script>

<div id="beer-history" class="coda-slider">
  <?php foreach ($collection as $item): ?>
  <?php $m = $item->getData(); ?>
    <div>
      <div class="hi-left-img-div">
        <img class="hi-left-img"
          alt="<?php echo $m['title']; ?>"
          src="<?php echo getMediaUrl($m['image_name']); ?>" />
      </div>
      <?php echo getContent($m['content']); ?>
    </div>
  <?php endforeach; ?>
</div>
